# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Downmixer Documentation

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]

theme:
  name: material
